"""
静态合约列表 - 当API无法获取时使用
包含币安和欧意全部USDT永续合约，不定期更新
"""
# 统计信息
# 欧意合约数量:261
# 币安合约数量: 542个
# 总计: 803个合约对
# 更新时间：2026-02-27 18:06:35

OKX_USDT_SWAPS = [
    "BTC-USDT-SWAP", "ETH-USDT-SWAP", "OKB-USDT-SWAP", "SOL-USDT-SWAP", "DOGE-USDT-SWAP", "XRP-USDT-SWAP", "BCH-USDT-SWAP", "PUMP-USDT-SWAP", "WLFI-USDT-SWAP", "LINEA-USDT-SWAP",
    "0G-USDT-SWAP", "1INCH-USDT-SWAP", "2Z-USDT-SWAP", "A-USDT-SWAP", "AAVE-USDT-SWAP", "ACH-USDT-SWAP", "ACT-USDT-SWAP", "ACU-USDT-SWAP", "ADA-USDT-SWAP", "AERO-USDT-SWAP",
    "AEVO-USDT-SWAP", "AGLD-USDT-SWAP", "AIXBT-USDT-SWAP", "ALGO-USDT-SWAP", "ALLO-USDT-SWAP", "AMZN-USDT-SWAP", "ANIME-USDT-SWAP", "APE-USDT-SWAP", "API3-USDT-SWAP", "APR-USDT-SWAP",
    "APT-USDT-SWAP", "AR-USDT-SWAP", "ARB-USDT-SWAP", "ARKM-USDT-SWAP", "ASTER-USDT-SWAP", "AT-USDT-SWAP", "ATH-USDT-SWAP", "ATOM-USDT-SWAP", "AUCTION-USDT-SWAP", "AVAX-USDT-SWAP",
    "AVNT-USDT-SWAP", "AXS-USDT-SWAP", "AZTEC-USDT-SWAP", "BABY-USDT-SWAP", "BAND-USDT-SWAP", "BARD-USDT-SWAP", "BAT-USDT-SWAP", "BEAT-USDT-SWAP", "BERA-USDT-SWAP", "BICO-USDT-SWAP",
    "BIGTIME-USDT-SWAP", "BIO-USDT-SWAP", "BLUR-USDT-SWAP", "BNB-USDT-SWAP", "BOME-USDT-SWAP", "BONK-USDT-SWAP", "BRETT-USDT-SWAP", "BREV-USDT-SWAP", "CC-USDT-SWAP", "CELO-USDT-SWAP",
    "CFX-USDT-SWAP", "CHZ-USDT-SWAP", "COAI-USDT-SWAP", "COIN-USDT-SWAP", "COMP-USDT-SWAP", "CORE-USDT-SWAP", "CRCL-USDT-SWAP", "CRO-USDT-SWAP", "CRV-USDT-SWAP", "CVX-USDT-SWAP",
    "DASH-USDT-SWAP", "DOOD-USDT-SWAP", "DOT-USDT-SWAP", "DYDX-USDT-SWAP", "EDEN-USDT-SWAP", "EGLD-USDT-SWAP", "EIGEN-USDT-SWAP", "ENA-USDT-SWAP", "ENJ-USDT-SWAP", "ENS-USDT-SWAP",
    "ENSO-USDT-SWAP", "ESP-USDT-SWAP", "ETC-USDT-SWAP", "ETHW-USDT-SWAP", "ETHFI-USDT-SWAP", "F-USDT-SWAP", "FARTCOIN-USDT-SWAP", "FIL-USDT-SWAP", "FLOKI-USDT-SWAP", "FLOW-USDT-SWAP",
    "FOGO-USDT-SWAP", "GALA-USDT-SWAP", "GAS-USDT-SWAP", "GIGGLE-USDT-SWAP", "GLM-USDT-SWAP", "GMT-USDT-SWAP", "GMX-USDT-SWAP", "GPS-USDT-SWAP", "GRASS-USDT-SWAP", "GRT-USDT-SWAP",
    "H-USDT-SWAP", "HBAR-USDT-SWAP", "HMSTR-USDT-SWAP", "HOME-USDT-SWAP", "HOOD-USDT-SWAP", "HUMA-USDT-SWAP", "HYPE-USDT-SWAP", "ICP-USDT-SWAP", "ICX-USDT-SWAP", "IMX-USDT-SWAP",
    "INIT-USDT-SWAP", "INJ-USDT-SWAP", "INTC-USDT-SWAP", "IOST-USDT-SWAP", "IOTA-USDT-SWAP", "IP-USDT-SWAP", "JELLYJELLY-USDT-SWAP", "JTO-USDT-SWAP", "JUP-USDT-SWAP", "KAITO-USDT-SWAP",
    "KGEN-USDT-SWAP", "KMNO-USDT-SWAP", "KSM-USDT-SWAP", "LA-USDT-SWAP", "LAB-USDT-SWAP", "LAYER-USDT-SWAP", "LDO-USDT-SWAP", "LIGHT-USDT-SWAP", "LINK-USDT-SWAP", "LIT-USDT-SWAP",
    "LPT-USDT-SWAP", "LQTY-USDT-SWAP", "LRC-USDT-SWAP", "LTC-USDT-SWAP", "LUNA-USDT-SWAP", "MAGIC-USDT-SWAP", "MANA-USDT-SWAP", "MASK-USDT-SWAP", "ME-USDT-SWAP", "MEME-USDT-SWAP",
    "MERL-USDT-SWAP", "METIS-USDT-SWAP", "MET-USDT-SWAP", "MEW-USDT-SWAP", "MINA-USDT-SWAP", "MMT-USDT-SWAP", "MON-USDT-SWAP", "MOODENG-USDT-SWAP", "MORPHO-USDT-SWAP", "MOVE-USDT-SWAP",
    "MSTR-USDT-SWAP", "MUBARAK-USDT-SWAP", "NEAR-USDT-SWAP", "NEIRO-USDT-SWAP", "NEO-USDT-SWAP", "NIGHT-USDT-SWAP", "NMR-USDT-SWAP", "NOT-USDT-SWAP", "OL-USDT-SWAP", "ONDO-USDT-SWAP",
    "ONE-USDT-SWAP", "ONT-USDT-SWAP", "OP-USDT-SWAP", "OPN-USDT-SWAP", "ORDI-USDT-SWAP", "ORDER-USDT-SWAP", "PARTI-USDT-SWAP", "PENGU-USDT-SWAP", "PENDLE-USDT-SWAP", "PEOPLE-USDT-SWAP",
    "PEPE-USDT-SWAP", "PI-USDT-SWAP", "PIEVERSE-USDT-SWAP", "PIPPIN-USDT-SWAP", "PLTR-USDT-SWAP", "PLUME-USDT-SWAP", "PNUT-USDT-SWAP", "POL-USDT-SWAP", "POPCAT-USDT-SWAP", "PROVE-USDT-SWAP",
    "PYTH-USDT-SWAP", "QTUM-USDT-SWAP", "RAVE-USDT-SWAP", "RAY-USDT-SWAP", "RECALL-USDT-SWAP", "RENDER-USDT-SWAP", "RESOLV-USDT-SWAP", "RIVER-USDT-SWAP", "RLS-USDT-SWAP", "RSR-USDT-SWAP",
    "RVN-USDT-SWAP", "S-USDT-SWAP", "SAHARA-USDT-SWAP", "SAND-USDT-SWAP", "SAPIEN-USDT-SWAP", "SATS-USDT-SWAP", "SEI-USDT-SWAP", "SENT-USDT-SWAP", "SHELL-USDT-SWAP", "SHIB-USDT-SWAP",
    "SIGN-USDT-SWAP", "SKY-USDT-SWAP", "SNX-USDT-SWAP", "SOON-USDT-SWAP", "SOPH-USDT-SWAP", "SPACE-USDT-SWAP", "SPK-USDT-SWAP", "SPX-USDT-SWAP", "SSV-USDT-SWAP", "STABLE-USDT-SWAP",
    "STRK-USDT-SWAP", "STX-USDT-SWAP", "SUI-USDT-SWAP", "SUSHI-USDT-SWAP", "SYRUP-USDT-SWAP", "TAO-USDT-SWAP", "THETA-USDT-SWAP", "TIA-USDT-SWAP", "TON-USDT-SWAP", "TRB-USDT-SWAP",
    "TRIA-USDT-SWAP", "TRUMP-USDT-SWAP", "TRUST-USDT-SWAP", "TRUTH-USDT-SWAP", "TRX-USDT-SWAP", "TSLA-USDT-SWAP", "TURBO-USDT-SWAP", "UMA-USDT-SWAP", "UNI-USDT-SWAP", "USDC-USDT-SWAP",
    "USELESS-USDT-SWAP", "VANA-USDT-SWAP", "VIRTUAL-USDT-SWAP", "W-USDT-SWAP", "WAL-USDT-SWAP", "WCT-USDT-SWAP", "WET-USDT-SWAP", "WIF-USDT-SWAP", "WLD-USDT-SWAP", "WOO-USDT-SWAP",
    "XAG-USDT-SWAP", "XAU-USDT-SWAP", "XLM-USDT-SWAP", "XPL-USDT-SWAP", "XPT-USDT-SWAP", "XTZ-USDT-SWAP", "YB-USDT-SWAP", "YFI-USDT-SWAP", "YGG-USDT-SWAP", "ZAMA-USDT-SWAP",
    "ZBT-USDT-SWAP", "ZEC-USDT-SWAP", "ZEN-USDT-SWAP", "ZETA-USDT-SWAP", "ZIL-USDT-SWAP", "ZK-USDT-SWAP", "ZKP-USDT-SWAP", "ZORA-USDT-SWAP", "ZRO-USDT-SWAP", "ZRX-USDT-SWAP",
    "XPD-USDT-SWAP"
]    

BINANCE_USDT_PERPETUALS = [
    "BTCUSDT", "ETHUSDT", "BCHUSDT", "XRPUSDT", "LTCUSDT", "TRXUSDT", "ETCUSDT", "LINKUSDT", "XLMUSDT", "ADAUSDT",
    "XMRUSDT", "DASHUSDT", "ZECUSDT", "XTZUSDT", "BNBUSDT", "ATOMUSDT", "ONTUSDT", "IOTAUSDT", "BATUSDT", "VETUSDT",
    "NEOUSDT", "QTUMUSDT", "IOSTUSDT", "THETAUSDT", "ALGOUSDT", "ZILUSDT", "KNCUSDT", "ZRXUSDT", "COMPUSDT", "DOGEUSDT",
    "KAVAUSDT", "BANDUSDT", "RLCUSDT", "SNXUSDT", "DOTUSDT", "YFIUSDT", "CRVUSDT", "TRBUSDT", "RUNEUSDT", "SUSHIUSDT",
    "EGLDUSDT", "SOLUSDT", "ICXUSDT", "STORJUSDT", "UNIUSDT", "AVAXUSDT", "ENJUSDT", "KSMUSDT", "NEARUSDT", "AAVEUSDT",
    "FILUSDT", "RSRUSDT", "LRCUSDT", "BELUSDT", "AXSUSDT", "ZENUSDT", "SKLUSDT", "GRTUSDT", "1INCHUSDT", "CHZUSDT",
    "SANDUSDT", "ANKRUSDT", "RVNUSDT", "SFPUSDT", "COTIUSDT", "CHRUSDT", "MANAUSDT", "ALICEUSDT", "HBARUSDT", "ONEUSDT",
    "DENTUSDT", "CELRUSDT", "HOTUSDT", "MTLUSDT", "OGNUSDT", "1000SHIBUSDT", "GTCUSDT", "BTCDOMUSDT", "IOTXUSDT", "C98USDT",
    "MASKUSDT", "ATAUSDT", "DYDXUSDT", "1000XECUSDT", "GALAUSDT", "CELOUSDT", "ARUSDT", "ARPAUSDT", "CTSIUSDT", "LPTUSDT",
    "ENSUSDT", "PEOPLEUSDT", "ROSEUSDT", "DUSKUSDT", "FLOWUSDT", "IMXUSDT", "API3USDT", "GMTUSDT", "APEUSDT", "WOOUSDT",
    "JASMYUSDT", "OPUSDT", "INJUSDT", "STGUSDT", "SPELLUSDT", "1000LUNCUSDT", "LUNA2USDT", "LDOUSDT", "ICPUSDT", "APTUSDT",
    "QNTUSDT", "FETUSDT", "HOOKUSDT", "MAGICUSDT", "TUSDT", "HIGHUSDT", "MINAUSDT", "ASTRUSDT", "PHBUSDT", "GMXUSDT",
    "CFXUSDT", "STXUSDT", "ACHUSDT", "SSVUSDT", "CKBUSDT", "TRUUSDT", "LQTYUSDT", "USDCUSDT", "IDUSDT", "ARBUSDT",
    "JOEUSDT", "TLMUSDT", "RDNTUSDT", "HFTUSDT", "XVSUSDT", "BLURUSDT", "EDUUSDT", "SUIUSDT", "1000PEPEUSDT", "1000FLOKIUSDT",
    "UMAUSDT", "NMRUSDT", "MAVUSDT", "XVGUSDT", "WLDUSDT", "PENDLEUSDT", "ARKMUSDT", "AGLDUSDT", "YGGUSDT", "DODOXUSDT",
    "BNTUSDT", "OXTUSDT", "SEIUSDT", "CYBERUSDT", "ARKUSDT", "BICOUSDT", "BIGTIMEUSDT", "WAXPUSDT", "BSVUSDT", "RIFUSDT",
    "POLYXUSDT", "GASUSDT", "POWRUSDT", "TIAUSDT", "CAKEUSDT", "MEMEUSDT", "TWTUSDT", "ORDIUSDT", "STEEMUSDT", "ILVUSDT",
    "NTRNUSDT", "KASUSDT", "BEAMXUSDT", "1000BONKUSDT", "PYTHUSDT", "SUPERUSDT", "USTCUSDT", "ONGUSDT", "ETHWUSDT", "JTOUSDT",
    "1000SATSUSDT", "AUCTIONUSDT", "1000RATSUSDT", "ACEUSDT", "MOVRUSDT", "NFPUSDT", "AIUSDT", "XAIUSDT", "WIFUSDT", "MANTAUSDT",
    "ONDOUSDT", "LSKUSDT", "ALTUSDT", "JUPUSDT", "ZETAUSDT", "RONINUSDT", "DYMUSDT", "PIXELUSDT", "STRKUSDT", "GLMUSDT",
    "PORTALUSDT", "TONUSDT", "AXLUSDT", "METISUSDT", "AEVOUSDT", "VANRYUSDT", "BOMEUSDT", "ETHFIUSDT", "ENAUSDT", "WUSDT",
    "TNSRUSDT", "SAGAUSDT", "TAOUSDT", "REZUSDT", "BBUSDT", "NOTUSDT", "TURBOUSDT", "IOUSDT", "ZKUSDT", "MEWUSDT",
    "LISTAUSDT", "ZROUSDT", "RENDERUSDT", "BANANAUSDT", "RAREUSDT", "GUSDT", "SYNUSDT", "SYSUSDT", "BRETTUSDT", "POPCATUSDT",
    "SUNUSDT", "DOGSUSDT", "MBOXUSDT", "FLUXUSDT", "RPLUSDT", "POLUSDT", "1MBABYDOGEUSDT", "NEIROUSDT", "FIDAUSDT", "FIOUSDT",
    "CATIUSDT", "HMSTRUSDT", "COSUSDT", "EIGENUSDT", "DIAUSDT", "1000CATUSDT", "SCRUSDT", "GOATUSDT", "MOODENGUSDT", "SAFEUSDT",
    "SANTOSUSDT", "COWUSDT", "CETUSUSDT", "1000000MOGUSDT", "GRASSUSDT", "DRIFTUSDT", "ACTUSDT", "PNUTUSDT", "HIPPOUSDT", "DEGENUSDT",
    "BANUSDT", "AKTUSDT", "SCRTUSDT", "1000CHEEMSUSDT", "1000WHYUSDT", "THEUSDT", "MORPHOUSDT", "CHILLGUYUSDT", "KAIAUSDT", "AEROUSDT",
    "ACXUSDT", "ORCAUSDT", "MOVEUSDT", "RAYSOLUSDT", "KOMAUSDT", "VIRTUALUSDT", "SPXUSDT", "MEUSDT", "AVAUSDT", "DEGOUSDT",
    "VELODROMEUSDT", "MOCAUSDT", "VANAUSDT", "PENGUUSDT", "LUMIAUSDT", "USUALUSDT", "AIXBTUSDT", "FARTCOINUSDT", "KMNOUSDT", "CGPTUSDT",
    "HIVEUSDT", "DEXEUSDT", "PHAUSDT", "GRIFFAINUSDT", "ZEREBROUSDT", "BIOUSDT", "COOKIEUSDT", "ALCHUSDT", "SWARMSUSDT", "SONICUSDT",
    "DUSDT", "PROMUSDT", "SUSDT", "SOLVUSDT", "ARCUSDT", "AVAAIUSDT", "TRUMPUSDT", "MELANIAUSDT", "VTHOUSDT", "ANIMEUSDT",
    "VINEUSDT", "PIPPINUSDT", "VVVUSDT", "BERAUSDT", "TSTUSDT", "LAYERUSDT", "HEIUSDT", "B3USDT", "IPUSDT", "GPSUSDT",
    "SHELLUSDT", "KAITOUSDT", "REDUSDT", "VICUSDT", "EPICUSDT", "BMTUSDT", "MUBARAKUSDT", "FORMUSDT", "TUTUSDT", "BROCCOLI714USDT",
    "BROCCOLIF3BUSDT", "SIRENUSDT", "BANANAS31USDT", "BRUSDT", "PLUMEUSDT", "NILUSDT", "PARTIUSDT", "JELLYJELLYUSDT", "MAVIAUSDT", "PAXGUSDT",
    "WALUSDT", "FUNUSDT", "MLNUSDT", "GUNUSDT", "ATHUSDT", "BABYUSDT", "FORTHUSDT", "PROMPTUSDT", "STOUSDT", "FHEUSDT",
    "KERNELUSDT", "WCTUSDT", "INITUSDT", "AERGOUSDT", "BANKUSDT", "DEEPUSDT", "HYPERUSDT", "JSTUSDT", "SIGNUSDT", "PUNDIXUSDT",
    "CTKUSDT", "AIOTUSDT", "DOLOUSDT", "HAEDALUSDT", "SXTUSDT", "ASRUSDT", "ALPINEUSDT", "B2USDT", "SYRUPUSDT", "DOODUSDT",
    "OGUSDT", "ZKJUSDT", "SKYAIUSDT", "NXPCUSDT", "CVCUSDT", "AGTUSDT", "AWEUSDT", "BUSDT", "SOONUSDT", "HUMAUSDT",
    "AUSDT", "SOPHUSDT", "MERLUSDT", "HYPEUSDT", "BDXNUSDT", "PUFFERUSDT", "1000000BOBUSDT", "LAUSDT", "HOMEUSDT", "RESOLVUSDT",
    "TAIKOUSDT", "SQDUSDT", "PUMPBTCUSDT", "SPKUSDT", "MYXUSDT", "FUSDT", "NEWTUSDT", "HUSDT", "OLUSDT", "SAHARAUSDT",
    "ICNTUSDT", "BULLAUSDT", "IDOLUSDT", "MUSDT", "PUMPUSDT", "CROSSUSDT", "AINUSDT", "CUSDT", "VELVETUSDT", "TACUSDT",
    "ERAUSDT", "TAUSDT", "CVXUSDT", "SLPUSDT", "ZORAUSDT", "TAGUSDT", "ESPORTSUSDT", "TREEUSDT", "A2ZUSDT", "PLAYUSDT",
    "NAORISUSDT", "TOWNSUSDT", "PROVEUSDT", "ALLUSDT", "INUSDT", "CARVUSDT", "AIOUSDT", "XNYUSDT", "USELESSUSDT", "DAMUSDT",
    "SAPIENUSDT", "XPLUSDT", "WLFIUSDT", "SOMIUSDT", "BASUSDT", "BTRUSDT", "MITOUSDT", "HEMIUSDT", "LINEAUSDT", "QUSDT",
    "ARIAUSDT", "TAKEUSDT", "PTBUSDT", "OPENUSDT", "FLOCKUSDT", "SKYUSDT", "AVNTUSDT", "HOLOUSDT", "XPINUSDT", "UBUSDT",
    "ZKCUSDT", "TOSHIUSDT", "STBLUSDT", "0GUSDT", "BARDUSDT", "ASTERUSDT", "TRADOORUSDT", "BLESSUSDT", "FLUIDUSDT", "COAIUSDT",
    "HANAUSDT", "MIRAUSDT", "AKEUSDT", "ORDERUSDT", "LIGHTUSDT", "XANUSDT", "FFUSDT", "VFYUSDT", "EDENUSDT", "NOMUSDT",
    "TRUTHUSDT", "2ZUSDT", "EVAAUSDT", "LYNUSDT", "KGENUSDT", "4USDT", "GIGGLEUSDT", "MONUSDT", "YBUSDT", "METUSDT",
    "EULUSDT", "ENSOUSDT", "CLOUSDT", "RECALLUSDT", "ZBTUSDT", "LABUSDT", "RIVERUSDT", "币安人生USDT", "BLUAIUSDT", "TURTLEUSDT",
    "APRUSDT", "ONUSDT", "KITEUSDT", "ATUSDT", "CCUSDT", "MMTUSDT", "TRUSTUSDT", "UAIUSDT", "FOLKSUSDT", "STABLEUSDT",
    "JCTUSDT", "ALLOUSDT", "CLANKERUSDT", "BEATUSDT", "PIEVERSEUSDT", "SENTUSDT", "BOBUSDT", "IRYSUSDT", "RLSUSDT", "POWERUSDT",
    "WETUSDT", "NIGHTUSDT", "USUSDT", "CYSUSDT", "RAVEUSDT", "ZKPUSDT", "GUAUSDT", "IRUSDT", "LITUSDT", "BREVUSDT",
    "COLLECTUSDT", "MAGMAUSDT", "ZAMAUSDT", "FOGOUSDT", "FRAXUSDT", "SPORTFUNUSDT", "AIAUSDT", "ACUUSDT", "我踏马来了USDT", "ELSAUSDT",
    "SKRUSDT", "SPACEUSDT", "FIGHTUSDT", "BIRBUSDT", "GWEIUSDT", "MEGAUSDT", "INXUSDT", "TRIAUSDT", "ESPUSDT", "AZTECUSDT",
    "OPNUSDT", "ROBOUSDT"
]

# 导出字典供其他模块使用
STATIC_SYMBOLS = {
    "okx": OKX_USDT_SWAPS,
    "binance": BINANCE_USDT_PERPETUALS
}


